[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "ligacloud"
authors = [{name = "Matheus Matos", email = "matheus@nanpos.com"}]
dynamic = ["version", "description"]
